/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 site_board.gltf 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/site_board.gltf");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0, 0, 0]}
        rotation={[1.5, 0.2, 0]}
        scale={[1.59 * 200, 0.375 * 200, 0.685 * 200]}
      >
        <group position={[-0.143, -0.567, 0.718]} scale={[0.104, 0.439, 0.241]}>
          <mesh
            geometry={nodes.Cube125_1.geometry}
            material={materials.Space}
          />
          <mesh
            geometry={nodes.Cube125_2.geometry}
            material={materials["White Keys 2"]}
          />
          <mesh
            geometry={nodes.Cube125_3.geometry}
            material={materials.Material}
          />
          <mesh
            geometry={nodes.Cube125_4.geometry}
            material={materials["Shift Arrow"]}
          />
          <mesh
            geometry={nodes.Cube125_5.geometry}
            material={materials["White Keys 1"]}
          />
          <mesh
            geometry={nodes.Cube125_6.geometry}
            material={materials["White Keys 7"]}
          />
          <mesh
            geometry={nodes.Cube125_7.geometry}
            material={materials["Black Keys 1"]}
          />
          <mesh
            geometry={nodes.Cube125_8.geometry}
            material={materials["Arrow.001"]}
          />
          <mesh
            geometry={nodes.Cube125_9.geometry}
            material={materials["White Keys 3"]}
          />
          <mesh
            geometry={nodes.Cube125_10.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            geometry={nodes.Cube125_11.geometry}
            material={materials["Black keys 4"]}
          />
          <mesh
            geometry={nodes.Cube125_12.geometry}
            material={materials["Black Keys 3"]}
          />
          <mesh geometry={nodes.Cube125_13.geometry} material={materials.Esc} />
          <mesh
            geometry={nodes.Cube125_14.geometry}
            material={materials["White Keys 4"]}
          />
          <mesh
            geometry={nodes.Cube125_15.geometry}
            material={materials["Black Keys 2"]}
          />
          <mesh
            geometry={nodes.Cube125_16.geometry}
            material={materials["White Keys 5"]}
          />
          <mesh
            geometry={nodes.Cube125_17.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            geometry={nodes.Cube125_18.geometry}
            material={materials["Material.001"]}
          />
        </group>
        <mesh
          geometry={nodes.Cube230.geometry}
          material={materials["Polycarbonate Case"]}
          position={[0.778, -1.016, -0.785]}
          rotation={[-0.028, 0, 0]}
          scale={[3.149, 13.351, 7.317]}
        />
        <mesh
          geometry={nodes.Cylinder.geometry}
          material={materials["Alumunium Knob"]}
          position={[0.854, -0.383, -0.669]}
          rotation={[0.059, 0, 0]}
          scale={[3.116, 13.472, 7.256]}
        />
        <mesh
          geometry={nodes.Plane002.geometry}
          material={materials["Polycarbonate Case"]}
          position={[-0.571, -0.58, 0.014]}
          rotation={[0.039, 0, 0]}
          scale={[3.149, 13.349, 7.322]}
        />
        <mesh
          geometry={nodes.Plane005.geometry}
          material={materials["Polycarbonate Case"]}
          position={[0.008, -0.95, -0.01]}
          rotation={[-0.005, 0, 0]}
          scale={[3.149, 13.354, 7.312]}
        />
        <mesh
          geometry={nodes.Plane006.geometry}
          material={materials["Polycarbonate Case"]}
          position={[-0.724, -1.008, 0.795]}
          rotation={[-0.005, 0, 0]}
          scale={[3.149, 13.354, 7.312]}
        />
        <mesh
          geometry={nodes.Plane010.geometry}
          material={materials["Polycarbonate Case"]}
          position={[-0.881, -1.05, -0.624]}
          rotation={[0.015, 0, 0]}
          scale={[3.149, 13.353, 7.314]}
        />
        <mesh
          geometry={nodes.Plane012.geometry}
          material={materials["Plate Metal"]}
          position={[0.01, -0.595, 0.039]}
          rotation={[-0.021, 0, 0]}
          scale={[3.149, 13.352, 7.315]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/site_board.gltf");
